### ISSUE TITLE
Issues de UI generales

### ISSUE THREAD

**Issue by fdodino** [FranSpinelli/SoloTravel-documentation#1]
- Chequear que el Font esté descargado (https://fonts.google.com/)
- Plata poner separador de miles para mostrar cuánto sale el paquete

**Comment by FranSpinelli** [comment]
- Chequear que el Font esté descargado (https://fonts.google.com/) (DONE)
- Plata poner separador de miles para mostrar cuánto sale el paquete (DONE)
